pages:
  stage: deploy
  image: python:latest
  script:
    - pip install mkdocs-material
    - pip install python-markdown-math
    - pip install "mkdocstrings[python]"
    - pip install mkdocs-jupyter
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
