site_name: WMSAN

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Overview: api_overview.md
  - User Guide: user_guide.md
  - Developer Guide: developer_guide.md
  - About: about.md
theme:
  name: readthedocs
  logo: logowmsan.png
  color_mode: auto
  features:
    - content.code.copy

repo_name: GitLab
repo_url: https://gricad-gitlab.univ-grenoble-alpes.fr/tomasetl/ww3-source-maps

markdown_extensions:
  - attr_list