site_name: WMSAN

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Overview:
    - 'Index': api_overview/api_overview.md
    - 'Read WW3 Files': api_overview/read_hs_p2l.md
    - 'Body Wave': api_overview/body_waves.md
    - 'Rayleigh Wave': api_overview/rayleigh_waves.md
    - 'Temporal Variations': api_overview/temporal_variations.md
    - 'Synthetic Cross-Correlation Functions': api_overview/synthetics.md
    - 'To noisi': api_overview/wmsan_to_noisi.md
  - User Guide: 
    - 'Tutorials': user_guide.md
  - Developer Guide: 
    - 'How to contribute ?': developer_guide.md
  - About: 
    - About: about.md

theme:
  name: readthedocs
  logo: img/logowmsan.png
  color_mode: auto
  features:
    - content.code.copy

repo_name: GitLab
repo_url: https://gricad-gitlab.univ-grenoble-alpes.fr/tomasetl/ww3-source-maps

markdown_extensions:
  - attr_list

plugins:
  - mkdocstrings
  - search